
name: wellon_partner_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.0+1

analyzer:
  enable-experiment:
    - non-nullable
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  #firebase_messaging: ^7.0.3
  firebase_messaging:
  url_launcher: ^5.4.2
  in_app_update:
  sqflite: ^1.3.1
  shared_preferences: ^0.5.7+3
  flutter_web_browser: ^0.12.0
  image_picker: ^0.6.4
  flash: ^1.1.0
  intl: ^0.16.1
  lottie: ^0.5.1
  connectivity: ^0.3.2
  path_provider: ^1.6.5
  flutter_svg: ^0.18.1
  package_info: ^0.4.0+16
  introduction_screen: ^1.0.8
  flutter_gifimage: ^1.0.0
  store_redirect: ^1.0.2
  clippy_flutter: ^1.1.1
  dropdown_formfield: ^0.1.2
  flutter_rating_bar: ^3.2.0+1
  pdf: ^1.7.0
  flutter_full_pdf_viewer: ^1.0.6
  basic_utils: ^1.2.0
  flutter_barcode_scanner: ^1.0.1
  open_appstore: ^1.0.2
  share_extend: "^1.1.5"
  share: ^0.6.5+2
  maps_launcher: ^1.2.2+1
  clipboard: ^0.1.2+8
  fluttertoast: ^7.1.1
  google_maps_flutter: ^0.5.28+1
  geolocator: ^5.3.1
  flutter_polyline_points: ^0.2.1
  google_fonts: ^1.1.0
  string_validator: ^0.1.4
  dotted_border: ^1.0.6
  google_maps_webservice: ^0.0.16
  http: ^0.12.0+4
  flutter_map_picker: ^0.1.2
  color: ^2.1.1
  flutter_google_places: ^0.2.6
  flutter_responsive_screen: ^1.0.0
  expansion_card: ^0.1.0
  page_transition:
  carousel_slider: ^2.3.1
  flutter_easyloading: ^2.2.2
  provider: ^4.1.3
  steps_indicator: ^1.2.0
  pinch_zoom_image_last: ^0.3.2
  webview_flutter: ^1.0.7
  native_updater:
#place_picker: ^0.9.14


dev_dependencies:
  flutter_launcher_icons: ^0.7.4
  flutter_launcher_name: ^0.0.1
  flutter_test:
    sdk: flutter
flutter_launcher_name:
  name: "Wellon Technician"
flutter_icons:
  android: "launcher"
  ios: true
  image_path: "images/launcher.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - images/
    - assets/noconnection.json
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
